### ISSUE TITLE
Please upload the dataset files

### ISSUE THREAD

**Issue by Abhijit-Dixit** [zgana/fpp3-python-readalong#1]
Hi @zgana !

I have not worked with R before, so if you could share the dataset files that you extracted from the fpp3 library it would be really helpful!

**Comment by zgana** [comment]
Hi @Abhijit-Dixit! I'm not sure if there are any licensing issues associated with re-publishing all of these datasets, so I'm hesitant to include them straight away without getting clarity on that.  However I did notice that @KeAWang uploaded them in [this fork](https://github.com/KeAWang/fpp3-python-readalong).

If either of you are able to determine the terms under which the datasets can be re-published then I would be happy to accept a PR that adds them in this upstream repo.

**Comment by Abhijit-Dixit** [comment]
Thanks for sharing the fork! If I get any confirmation about the licensing issues, I'll let you know.
