### ISSUE TITLE
Download the datasets from fpp3 package 

### ISSUE THREAD

**Issue by GreenAnalytics** [zgana/fpp3-python-readalong#2]
Hi Zgana, 
I am sorry if this is not the appropriate channel, but I did not find any other mean to contact you. I wanted to try the codes on my own, but I dont have the datasets and dont want to install R just to do it. Do you have it in any place so I can download it?
many thanks,
Felipe

**Comment by loginsanjeev** [comment]
I have the same issue. Where can I download these datasets you are reading on your notebook?

**Comment by asifm** [comment]
For anyone who needs the datasets, I created a repo here: [asifm/fpp3-data](https://github.com/asifm/fpp3-data/tree/main)

**Comment by zgana** [comment]
Thanks for posting the datasets @asifm!  I just did a round of updates, so now the files are incorporated into this repository.
